name: deploy dev

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::133506990706:role/GitHubActionsRole
          role-session-name: GithubActionsSession

      - name: Install dependencies
        run: npm ci

      - name: Deploy to temporary stage called 'ci-dev'
        run: npx sls deploy --stage ci-dev

      - name: Export env for ci-dev
        run: npx sls export-env --all --stage ci-dev --output .env

      - name: Run integration tests
        run: npx cross-env TEST_MODE=handler jest --silent

      - name: Run acceptance tests
        run: npx cross-env TEST_MODE=http jest --silent

      - name: Remove temporary stage called 'ci-dev'
        run: npx sls remove --stage ci-dev

      - name: Deploy to dev
        run: npx sls deploy