name: deploy dev

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::133506990706:role/GitHubActionsRole
          role-session-name: GitHubActionsSession
      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test

      - name: Deploy to dev
        run: npx sls deploy

      - name: Run acceptance tests
        run: npm run test:acceptance